version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    privileged: true
    user: root
    ports:
      - 8022:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - /PEASE/ENTER/PATH/FOR/DATA:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker
