apiVersion: v1
kind: Service
metadata:
  name: dashlink-service
spec:
  type: LoadBalancer # This exposes the service externally
  selector:
    app: dashlink
  ports:
  - port: 5027 # Internal port of your app
    targetPort: 5027
    protocol: TCP

