apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashlink-deployment
  namespace: test-gitops  # Ensure you're in the right namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashlink
  template:
    metadata:
      labels:
        app: dashlink
    spec:
      containers:
      - name: dashlink
        image: sohaib.hub/gitops_demo:1
        ports:
        - containerPort: 5027
        volumeMounts:
        - name: dashlink-data
          mountPath: /app/data
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: dashlink-data
        hostPath:
          path: /home/devk3s/dashlink
          type: Directory
      imagePullSecrets:
      - name: regcred  # Ensure the secret exists in the dashlink namespace
